data_processing_constants:
  vref: 3.300
  acc_sensitivity: 300.0
  gyro_sensitivity: 3.330
  static_period: 5.000
  adc_max: 1023
training_parameters:
  step_size: 0.005
  num_iterations: 300
  eps_numerical_stability: 0.000001
  debug: true
other_configs:
  datasets:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  quaternion_eps_numerical_stability: 0.000001
  path_to_datasets: "data/testset/"
  plot_figures_folder: "plot_images/"
  panorama_images_folder: "panorama_images/"
  no_force_train: False
  use_vicon: False
results:
  folder: "results/"
  optimized_quaternion_fname: "q_optim"
  motion_model_quaternion_fname: "q_motion"
  acceleration_estimate_fname: "a_estim"
  obsrv_model_fname: "a_obsrv"
  costs_record_fname: "costs"


