data_processing_constants:
  vref: 3.300
  acc_sensitivity: 300.0
  gyro_sensitivity: 3.330
  static_period: 5.000
  adc_max: 1023
training_parameters:
  step_size: 0.01
  num_iterations: 300
  eps_numerical_stability: 0.000001
  debug: true
other_configs:
  datasets:
    - 9
  quaternion_eps_numerical_stability: 0.000001
  path_to_datasets: "data/"
  save_image_folder: "plot_images/"
